import { FREELAND_SPECS, TEXTURES } from './keys';

const ROOT = '/assets/freeland/medium';
const PLAYTEST_UNITS_ROOT = '/assets/playtest-units';

export const assetManifest = [
  { kind: 'sheet', key: TEXTURES.grassBase, path: `${ROOT}/terrains/g.png`, frameConfig: { frameWidth: 96, frameHeight: 48 } },
  { kind: 'sheet', key: TEXTURES.savannahBase, path: `${ROOT}/terrains/p.png`, frameConfig: { frameWidth: 96, frameHeight: 48 } },
  { kind: 'sheet', key: TEXTURES.desertBase, path: `${ROOT}/terrains/d.png`, frameConfig: { frameWidth: 96, frameHeight: 48 } },
  { kind: 'sheet', key: TEXTURES.tundraBase, path: `${ROOT}/terrains/t.png`, frameConfig: { frameWidth: 96, frameHeight: 48 } },
  { kind: 'text', key: FREELAND_SPECS.grassTerrain, path: `${ROOT}/terrains/g.spec` },
  { kind: 'text', key: FREELAND_SPECS.savannahTerrain, path: `${ROOT}/terrains/p.spec` },
  { kind: 'text', key: FREELAND_SPECS.desertTerrain, path: `${ROOT}/terrains/d.spec` },
  { kind: 'text', key: FREELAND_SPECS.tundraTerrain, path: `${ROOT}/terrains/t.spec` },
  { kind: 'text', key: FREELAND_SPECS.swampTerrain, path: `${ROOT}/terrains/swamps.spec` },
  { kind: 'text', key: FREELAND_SPECS.mountainTerrain, path: `${ROOT}/terrains/mountains.spec` },
  { kind: 'sheet', key: TEXTURES.forestOverlay, path: `${ROOT}/terrains/forests.png`, frameConfig: { frameWidth: 96, frameHeight: 66 } },
  { kind: 'sheet', key: TEXTURES.jungleOverlay, path: `${ROOT}/terrains/jungles.png`, frameConfig: { frameWidth: 96, frameHeight: 66 } },
  { kind: 'sheet', key: TEXTURES.hillOverlay, path: `${ROOT}/terrains/hills.png`, frameConfig: { frameWidth: 96, frameHeight: 48 } },
  { kind: 'sheet', key: TEXTURES.swampOverlay, path: `${ROOT}/terrains/swamps.png`, frameConfig: { frameWidth: 96, frameHeight: 48 } },
  { kind: 'sheet', key: TEXTURES.mountainOverlay, path: `${ROOT}/terrains/mountains.png`, frameConfig: { frameWidth: 96, frameHeight: 66 } },
  { kind: 'sheet', key: TEXTURES.oceanBase, path: `${ROOT}/terrains/oceans.png`, frameConfig: { frameWidth: 48, frameHeight: 24 } },
  { kind: 'sheet', key: TEXTURES.riverOverlay, path: `${ROOT}/terrains/rivers.png`, frameConfig: { frameWidth: 96, frameHeight: 48 } },
  { kind: 'image', key: TEXTURES.oasisOverlay, path: `${ROOT}/terrains/oasis.png` },
  { kind: 'sheet', key: TEXTURES.cities, path: `${ROOT}/cities/cities.png`, frameConfig: { frameWidth: 96, frameHeight: 72 } },
  { kind: 'sheet', key: TEXTURES.units, path: `${ROOT}/units.png`, frameConfig: { frameWidth: 64, frameHeight: 48 } },
  { kind: 'sheet', key: TEXTURES.fog, path: `${ROOT}/fog.png`, frameConfig: { frameWidth: 96, frameHeight: 48 } },
  { kind: 'text', key: FREELAND_SPECS.fog, path: `${ROOT}/fog.spec` },
  { kind: 'sheet', key: TEXTURES.selection, path: `${ROOT}/select-alpha.png`, frameConfig: { frameWidth: 96, frameHeight: 48 } },
  { kind: 'image', key: TEXTURES.druidSpearInfantry, path: `${PLAYTEST_UNITS_ROOT}/druid_spear_infantry.png` },
  { kind: 'image', key: TEXTURES.druidArcher, path: `${PLAYTEST_UNITS_ROOT}/druid_archer.png` },
  { kind: 'image', key: TEXTURES.druidHealer, path: `${PLAYTEST_UNITS_ROOT}/druid_healer.png` },
  { kind: 'image', key: TEXTURES.druidWizard, path: `${PLAYTEST_UNITS_ROOT}/druid_wizard.png` },
  { kind: 'image', key: TEXTURES.steppeHorseArcher, path: `${PLAYTEST_UNITS_ROOT}/steppe_horse_archer.png` },
  { kind: 'image', key: TEXTURES.steppeSpearInfantry, path: `${PLAYTEST_UNITS_ROOT}/steppe_spear_infantry.png` },
  { kind: 'image', key: TEXTURES.steppeRaiders, path: `${PLAYTEST_UNITS_ROOT}/steppe_raiders.png` },
  { kind: 'image', key: TEXTURES.steppePriestess, path: `${PLAYTEST_UNITS_ROOT}/steppe_priestess.png` },
  { kind: 'image', key: TEXTURES.steppeWarlord, path: `${PLAYTEST_UNITS_ROOT}/steppe_warlord.png` },
  { kind: 'image', key: TEXTURES.jungleSpearman, path: `${PLAYTEST_UNITS_ROOT}/jungle_spearman.png` },
  { kind: 'image', key: TEXTURES.jungleArcher, path: `${PLAYTEST_UNITS_ROOT}/jungle_archer.png` },
  { kind: 'image', key: TEXTURES.jungleBlowgun, path: `${PLAYTEST_UNITS_ROOT}/jungle_blowgun.png` },
  { kind: 'image', key: TEXTURES.junglePriest, path: `${PLAYTEST_UNITS_ROOT}/jungle_priest.png` },
  { kind: 'image', key: TEXTURES.jungleSerpent, path: `${PLAYTEST_UNITS_ROOT}/jungle_serpent.png` },
  { kind: 'image', key: TEXTURES.hillSpearInfantry, path: `${PLAYTEST_UNITS_ROOT}/hill_spear_infantry.png` },
  { kind: 'image', key: TEXTURES.hillArcher, path: `${PLAYTEST_UNITS_ROOT}/hill_archer.png` },
  { kind: 'image', key: TEXTURES.hillFortressArcher, path: `${PLAYTEST_UNITS_ROOT}/hill_fortress_archer.png` },
  { kind: 'image', key: TEXTURES.hillCatapult, path: `${PLAYTEST_UNITS_ROOT}/hill_catapult.png` },
  { kind: 'image', key: TEXTURES.hillSiegeGolem, path: `${PLAYTEST_UNITS_ROOT}/hill_siege_golem.png` },
  { kind: 'image', key: TEXTURES.hillFortress, path: `${PLAYTEST_UNITS_ROOT}/hill_fortress.png` },
  { kind: 'image', key: TEXTURES.hillEngineer, path: `${PLAYTEST_UNITS_ROOT}/Hill_Engineer.png` },
  { kind: 'image', key: TEXTURES.pirateInfantry, path: `${PLAYTEST_UNITS_ROOT}/pirate_infantry.png` },
  { kind: 'image', key: TEXTURES.pirateRanged, path: `${PLAYTEST_UNITS_ROOT}/pirate_ranged.png` },
  { kind: 'image', key: TEXTURES.pirateSlaver, path: `${PLAYTEST_UNITS_ROOT}/pirate_slaver.png` },
  { kind: 'image', key: TEXTURES.pirateSlaverShip, path: `${PLAYTEST_UNITS_ROOT}/pirate_slaver_ship.png` },
  { kind: 'image', key: TEXTURES.pirateGalley, path: `${PLAYTEST_UNITS_ROOT}/pirate_galley.png` },
  { kind: 'image', key: TEXTURES.desertCamel, path: `${PLAYTEST_UNITS_ROOT}/desert_camel.png` },
  { kind: 'image', key: TEXTURES.desertSpearman, path: `${PLAYTEST_UNITS_ROOT}/desert_spearman.png` },
  { kind: 'image', key: TEXTURES.desertArcher, path: `${PLAYTEST_UNITS_ROOT}/desert_archer.png` },
  { kind: 'image', key: TEXTURES.desertCamelLancers, path: `${PLAYTEST_UNITS_ROOT}/desert_camel_lancers.png` },
  { kind: 'image', key: TEXTURES.desertImmortal, path: `${PLAYTEST_UNITS_ROOT}/desert_immortal.png` },
  { kind: 'image', key: TEXTURES.savannahSpearman, path: `${PLAYTEST_UNITS_ROOT}/savannah_spearman.png` },
  { kind: 'image', key: TEXTURES.savannahJavelin, path: `${PLAYTEST_UNITS_ROOT}/savannah_javelin.png` },
  { kind: 'image', key: TEXTURES.savannahElephant, path: `${PLAYTEST_UNITS_ROOT}/savannah_elephant.png` },
  { kind: 'image', key: TEXTURES.savannahChariot, path: `${PLAYTEST_UNITS_ROOT}/savannah_chariot.png` },
  { kind: 'image', key: TEXTURES.riverSpearman, path: `${PLAYTEST_UNITS_ROOT}/river_spearman.png` },
  { kind: 'image', key: TEXTURES.riverCanoe, path: `${PLAYTEST_UNITS_ROOT}/river_canoe.png` },
  { kind: 'image', key: TEXTURES.riverRaiders, path: `${PLAYTEST_UNITS_ROOT}/river_raiders.png` },
  { kind: 'image', key: TEXTURES.riverPriestess, path: `${PLAYTEST_UNITS_ROOT}/river_priestess.png` },
  { kind: 'image', key: TEXTURES.riverCrocodile, path: `${PLAYTEST_UNITS_ROOT}/river_crocodile.png` },
  { kind: 'image', key: TEXTURES.frostSpearman, path: `${PLAYTEST_UNITS_ROOT}/frost_spearman.png` },
  { kind: 'image', key: TEXTURES.frostArcher, path: `${PLAYTEST_UNITS_ROOT}/frost_archer.png` },
  { kind: 'image', key: TEXTURES.frostIceDefenders, path: `${PLAYTEST_UNITS_ROOT}/frost_ice_defenders.png` },
  { kind: 'image', key: TEXTURES.frostPriest, path: `${PLAYTEST_UNITS_ROOT}/frost_priest.png` },
  { kind: 'image', key: TEXTURES.frostPolarBear, path: `${PLAYTEST_UNITS_ROOT}/frost_polar_bear.png` },
  // Rear-facing (flipped) sprites
  { kind: 'image', key: TEXTURES.druidSpearInfantryRear, path: `${PLAYTEST_UNITS_ROOT}/druid_spear_infantry_flipped.png` },
  { kind: 'image', key: TEXTURES.druidArcherRear, path: `${PLAYTEST_UNITS_ROOT}/druid_archer_flipped.png` },
  { kind: 'image', key: TEXTURES.druidHealerRear, path: `${PLAYTEST_UNITS_ROOT}/druid_healer_flipped.png` },
  { kind: 'image', key: TEXTURES.druidWizardRear, path: `${PLAYTEST_UNITS_ROOT}/druid_wizard_flipped.png` },
  { kind: 'image', key: TEXTURES.steppeHorseArcherRear, path: `${PLAYTEST_UNITS_ROOT}/steppe_horse_archer_flipped.png` },
  { kind: 'image', key: TEXTURES.steppeSpearInfantryRear, path: `${PLAYTEST_UNITS_ROOT}/steppe_spear_infantry_flipped.png` },
  { kind: 'image', key: TEXTURES.steppeRaidersRear, path: `${PLAYTEST_UNITS_ROOT}/steppe_raiders_flipped.png` },
  { kind: 'image', key: TEXTURES.steppePriestessRear, path: `${PLAYTEST_UNITS_ROOT}/steppe_priestess_flipped.png` },
  { kind: 'image', key: TEXTURES.steppeWarlordRear, path: `${PLAYTEST_UNITS_ROOT}/steppe_warlord_flipped.png` },
  { kind: 'image', key: TEXTURES.jungleSpearmanRear, path: `${PLAYTEST_UNITS_ROOT}/jungle_spearman_flipped.png` },
  { kind: 'image', key: TEXTURES.jungleArcherRear, path: `${PLAYTEST_UNITS_ROOT}/jungle_archer_flipped.png` },
  { kind: 'image', key: TEXTURES.jungleBlowgunRear, path: `${PLAYTEST_UNITS_ROOT}/jungle_blowgun_flipped.png` },
  { kind: 'image', key: TEXTURES.junglePriestRear, path: `${PLAYTEST_UNITS_ROOT}/jungle_priest_flipped.png` },
  { kind: 'image', key: TEXTURES.jungleSerpentRear, path: `${PLAYTEST_UNITS_ROOT}/jungle_serpent_flipped.png` },
  { kind: 'image', key: TEXTURES.hillSpearInfantryRear, path: `${PLAYTEST_UNITS_ROOT}/hill_spear_infantry_flipped.png` },
  { kind: 'image', key: TEXTURES.hillArcherRear, path: `${PLAYTEST_UNITS_ROOT}/hill_archer_flipped.png` },
  { kind: 'image', key: TEXTURES.hillFortressArcherRear, path: `${PLAYTEST_UNITS_ROOT}/hill_fortress_archer_flipped.png` },
  { kind: 'image', key: TEXTURES.hillCatapultRear, path: `${PLAYTEST_UNITS_ROOT}/hill_catapult_flipped.png` },
  { kind: 'image', key: TEXTURES.hillSiegeGolemRear, path: `${PLAYTEST_UNITS_ROOT}/hill_siege_golem_flipped.png` },
  { kind: 'image', key: TEXTURES.hillFortressRear, path: `${PLAYTEST_UNITS_ROOT}/hill_fortress_flipped.png` },
  { kind: 'image', key: TEXTURES.hillEngineerRear, path: `${PLAYTEST_UNITS_ROOT}/Hill_Engineer_flipped.png` },
  { kind: 'image', key: TEXTURES.pirateInfantryRear, path: `${PLAYTEST_UNITS_ROOT}/pirate_infantry_flipped.png` },
  { kind: 'image', key: TEXTURES.pirateRangedRear, path: `${PLAYTEST_UNITS_ROOT}/pirate_ranged_flipped.png` },
  { kind: 'image', key: TEXTURES.pirateSlaverRear, path: `${PLAYTEST_UNITS_ROOT}/pirate_slaver_flipped.png` },
  { kind: 'image', key: TEXTURES.pirateSlaverShipRear, path: `${PLAYTEST_UNITS_ROOT}/pirate_slaver_ship_flipped.png` },
  { kind: 'image', key: TEXTURES.pirateGalleyRear, path: `${PLAYTEST_UNITS_ROOT}/pirate_galley_flipped.png` },
  { kind: 'image', key: TEXTURES.desertCamelRear, path: `${PLAYTEST_UNITS_ROOT}/desert_camel_flipped.png` },
  { kind: 'image', key: TEXTURES.desertSpearmanRear, path: `${PLAYTEST_UNITS_ROOT}/desert_spearman_flipped.png` },
  { kind: 'image', key: TEXTURES.desertArcherRear, path: `${PLAYTEST_UNITS_ROOT}/desert_archer_flipped.png` },
  { kind: 'image', key: TEXTURES.desertCamelLancersRear, path: `${PLAYTEST_UNITS_ROOT}/desert_camel_lancers_flipped.png` },
  { kind: 'image', key: TEXTURES.desertImmortalRear, path: `${PLAYTEST_UNITS_ROOT}/desert_immortal_flipped.png` },
  { kind: 'image', key: TEXTURES.savannahSpearmanRear, path: `${PLAYTEST_UNITS_ROOT}/savannah_spearman_flipped.png` },
  { kind: 'image', key: TEXTURES.savannahJavelinRear, path: `${PLAYTEST_UNITS_ROOT}/savannah_javelin_flipped.png` },
  { kind: 'image', key: TEXTURES.savannahElephantRear, path: `${PLAYTEST_UNITS_ROOT}/savannah_elephant_flipped.png` },
  { kind: 'image', key: TEXTURES.savannahChariotRear, path: `${PLAYTEST_UNITS_ROOT}/savannah_chariot_flipped.png` },
  { kind: 'image', key: TEXTURES.riverSpearmanRear, path: `${PLAYTEST_UNITS_ROOT}/river_spearman_flipped.png` },
  { kind: 'image', key: TEXTURES.riverCanoeRear, path: `${PLAYTEST_UNITS_ROOT}/river_canoe_flipped.png` },
  { kind: 'image', key: TEXTURES.riverRaidersRear, path: `${PLAYTEST_UNITS_ROOT}/river_raiders_flipped.png` },
  { kind: 'image', key: TEXTURES.riverPriestessRear, path: `${PLAYTEST_UNITS_ROOT}/river_priestess_flipped.png` },
  { kind: 'image', key: TEXTURES.riverCrocodileRear, path: `${PLAYTEST_UNITS_ROOT}/river_crocodile_flipped.png` },
  { kind: 'image', key: TEXTURES.frostSpearmanRear, path: `${PLAYTEST_UNITS_ROOT}/frost_spearman_flipped.png` },
  { kind: 'image', key: TEXTURES.frostArcherRear, path: `${PLAYTEST_UNITS_ROOT}/frost_archer_flipped.png` },
  { kind: 'image', key: TEXTURES.frostIceDefendersRear, path: `${PLAYTEST_UNITS_ROOT}/frost_ice_defenders_flipped.png` },
  { kind: 'image', key: TEXTURES.frostPriestRear, path: `${PLAYTEST_UNITS_ROOT}/frost_priest_flipped.png` },
  { kind: 'image', key: TEXTURES.frostPolarBearRear, path: `${PLAYTEST_UNITS_ROOT}/frost_polar_bear_flipped.png` },
] as const;
